"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ch_l$asqwt38h!pp%*yc4b3pdcpz24zkda=i8u!^-la*4)d6+2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["admin.ishbozor.uz"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #apps
    'workers'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'baza',
        'USER': 'postgres',
        'PASSWORD': 'Lazizbek1',
        'HOST': 'localhost',  # Agar PostgreSQL boshqa serverda bo'lsa, uning IP manzilini kiriting
        'PORT': '5432',  # PostgreSQL-ning standart porti
    }
}

CSRF_COOKIE_SECURE = True  # faqat HTTPS orqali yuborish
CSRF_COOKIE_DOMAIN = ".ishbozor.uz"  # Agar barcha subdomenlar uchun kerak bo'lsa
CSRF_COOKIE_NAME = "csrftoken"  # CSRF token nomi

# CSRF uchun trusted originlar
CSRF_TRUSTED_ORIGINS = [
    'https://admin.ishbozor.uz',  # Trust originni qo'shish
]

# CSRF so'rovlarini boshqarish
CSRF_USE_SESSIONS = True  # Seans orqali CSRF tokenlarini saqlash
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True



BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'  

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",  # Barcha statik fayllarni shu yerga joylaysiz
]

# Gunicorn/Nginx serverida foydalanish uchun:
STATIC_ROOT = BASE_DIR / "static"  # `collectstatic` ishlaganda bu yerga jamlanadi

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
